"""
ToolGate Tool Calling Pipeline

Implements contract-based forward execution loop
"""

from typing import Dict, Any, List, Optional, Callable, Set
from dataclasses import dataclass, field
import json

from ..core.symbolic_state import SymbolicState
from ..core.tool_executor import ToolExecutor
from ..contracts.contract import ToolContract
from ..verification.precondition_checker import PreconditionChecker
from ..verification.postcondition_verifier import PostconditionVerifier
from ..retrieval.tool_retriever import ToolRetriever
from ..state.state_manager import StateManager
from ..llm.gpt_client import GPTClient
from ..llm.prompt_templates import ReActPromptTemplate


@dataclass
class Action:
    """Action generated by LLM reasoning"""
    type: str  # "answer" or "start_call_tool"
    content: str  # Answer content or sub-goal description
    tool_name: Optional[str] = None  # Tool name if calling tool
    tool_params: Optional[Dict[str, Any]] = None  # Tool parameters


@dataclass
class ExecutionTrace:
    """Execution trace"""
    step: int
    state: SymbolicState
    action: Optional[Action] = None
    tool_called: Optional[str] = None
    tool_result: Optional[Dict[str, Any]] = None
    verification_result: Optional[Dict[str, Any]] = None
    state_updated: bool = False


class ToolGatePipeline:
    """
    ToolGate Tool Calling Pipeline
    
    Implements contract-based forward execution loop
    """
    
    def __init__(self,
                 tool_contracts: Dict[str, ToolContract],
                 llm_client: Optional[GPTClient] = None,
                 llm_reasoner: Optional[Callable] = None,
                 prompt_template: Optional[ReActPromptTemplate] = None,
                 tool_executor: Optional[ToolExecutor] = None,
                 state_manager: Optional[StateManager] = None,
                 retriever: Optional[ToolRetriever] = None,
                 max_steps: int = 10,
                 use_llm_verifier: bool = False):
        """
        Initialize pipeline
        
        Args:
            tool_contracts: Tool contract dictionary {tool_name: contract}
            llm_client: LLM client (GPTClient)
            llm_reasoner: LLM reasoning function (deprecated, use llm_client and prompt_template)
            prompt_template: Prompt template
            tool_executor: Tool executor
            state_manager: State manager
            retriever: Tool retriever
            max_steps: Maximum execution steps
            use_llm_verifier: Whether to use LLM verifier
        """
        self.tool_contracts = tool_contracts
        self.llm_client = llm_client
        self.llm_reasoner = llm_reasoner  # Keep for backward compatibility
        self.prompt_template = prompt_template or ReActPromptTemplate()
        self.tool_executor = tool_executor or ToolExecutor()
        self.state_manager = state_manager or StateManager()
        self.retriever = retriever or ToolRetriever(tool_contracts)
        self.max_steps = max_steps
        self.use_llm_verifier = use_llm_verifier
        
        # Initialize verifiers
        self.precondition_checker = PreconditionChecker(
            use_llm_verifier=use_llm_verifier
        )
        self.postcondition_verifier = PostconditionVerifier(
            use_llm_verifier=use_llm_verifier
        )
        
        # Execution trace and conversation history
        self.trace: List[ExecutionTrace] = []
        self.failed_tools: Set[str] = set()
        self.conversation_history: List[Dict[str, str]] = []
        self.tool_results_history: List[str] = []  # Store tool results (wrapped)
    
    def run(self, query: str, history: Optional[List[Dict[str, Any]]] = None,
           initial_entities: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Run pipeline
        
        Args:
            query: User query
            history: Conversation history
            initial_entities: Initial entities (optional)
        
        Returns:
            Execution result dictionary
        """
        # Initialize state
        S_k = self.state_manager.initialize_state(query, history, initial_entities)
        k = 0
        self.trace = []
        self.failed_tools = set()
        self.conversation_history = history.copy() if history else []
        self.tool_results_history = []
        
        while k < self.max_steps:
            # 1. LLM reasoning
            action = self._llm_reason(query, self.conversation_history, S_k)
            
            trace_entry = ExecutionTrace(
                step=k,
                state=S_k,
                action=action
            )
            
            # 2. Determine action type
            if action.type == "answer":
                # Return answer directly
                trace_entry.action = action
                self.trace.append(trace_entry)
                
                # Note: Conversation history already has full LLM response added in _llm_reason
                # Don't add again here to avoid duplication
                # If _llm_reason didn't add (e.g., using custom llm_reasoner), add here
                if not self.llm_client and not self.llm_reasoner:
                    # Only add if not using LLM client
                    self.conversation_history.append({
                        "role": "assistant",
                        "content": action.content
                    })
                
                return {
                    "answer": action.content,
                    "final_state": S_k.to_dict(),
                    "trace": self._format_trace(),
                    "conversation_history": self.conversation_history
                }
            
            elif action.type == "start_call_tool":
                # Enter tool calling phase
                result = self._try_tool_call(
                    query, S_k, action, trace_entry
                )
                
                if isinstance(result, tuple):
                    tool_success, new_state = result
                else:
                    tool_success = result
                    new_state = S_k
                
                if tool_success:
                    # Tool call successful, update state
                    S_k = new_state
                    k += 1
                else:
                    # All tools failed, feed failure info back to LLM
                    # Encourage LLM to continue trying other approaches instead of giving up early
                    failure_message = (
                        "<start_tool_result>\n"
                        "Tool call failed: The currently attempted tool cannot be called successfully. "
                        "Possible reasons: Precondition not satisfied, tool execution failed, or postcondition verification failed.\n\n"
                        "**Important: Please don't give up!**\n"
                        "- Consider trying other tools: Different tools may provide similar information\n"
                        "- Try different parameters: The current tool may need different input parameters\n"
                        "- Try alternative approaches: Think about other methods to obtain required information\n"
                        "- Check state information: Current state may already contain some useful information\n\n"
                        "You should only provide a final answer in the following cases:\n"
                        "1. You have successfully obtained enough information to answer the question, OR\n"
                        "2. You have tried all reasonable tool options and can provide a helpful answer based on available information\n\n"
                        "Please continue thinking and trying other approaches.\n"
                        "<end_tool_result>"
                    )
                    self.tool_results_history.append(failure_message)
                    self.conversation_history.append({
                        "role": "user",
                        "content": failure_message
                    })
                    
                    # Record trace (even if failed)
                    self.trace.append(trace_entry)
                    
                    k += 1
                    if k >= self.max_steps:
                        # Reached max steps, return current state
                        return {
                            "answer": "Unable to complete task, all tool calls failed",
                            "final_state": S_k.to_dict(),
                            "trace": self._format_trace(),
                            "conversation_history": self.conversation_history
                        }
            else:
                # Unknown action type
                k += 1
                continue
        
        # Reached max steps
        return {
            "answer": "Reached maximum execution steps",
            "final_state": S_k.to_dict(),
            "trace": self._format_trace()
        }
    
    def _llm_reason(self, query: str, history: Optional[List[Dict[str, Any]]],
                   state: SymbolicState) -> Action:
        """
        LLM reasoning
        
        Determine whether to generate answer or call tool
        Supports special markers: <start_call_tool>, <end_call_tool>
        """
        # Prefer llm_client
        if self.llm_client:
            # Build prompt
            messages = self.prompt_template.format_messages(
                query=query,
                state=state,
                history=history,
                tool_results=self.tool_results_history
            )
            
            # Call LLM (set stop tokens to support special markers)
            stop_tokens = ["<end_call_tool>", "\n\nUser:", "\n\n**"]
            response = self.llm_client.generate_with_history(
                messages=messages,
                stop=stop_tokens
            )
            
            # Parse response, extract action
            action_dict = self.prompt_template.extract_action(response)
            
            # Update conversation history
            self.conversation_history.append({
                "role": "assistant",
                "content": response
            })
            
            return Action(
                type=action_dict["type"],
                content=action_dict["content"],
                tool_name=None
            )
        
        # Backward compatibility: use custom llm_reasoner
        if self.llm_reasoner:
            return self.llm_reasoner(query, history, state)
        
        # Default behavior: if state has enough info, return answer; otherwise call tool
        # This is a simplified implementation, should use real LLM in practice
        state_summary = state.get_summary()
        
        # Simplified: if state is empty or insufficient info, try calling tool
        if len(state._fields) == 0:
            return Action(
                type="start_call_tool",
                content="Need to obtain information",
                tool_name=None
            )
        else:
            # Assume enough info, return answer
            return Action(
                type="answer",
                content=f"Answer based on state {state_summary}"
            )
    
    def _try_tool_call(self, query: str, state: SymbolicState,
                      action: Action, trace_entry: ExecutionTrace):
        """
        Try tool call
        
        Returns:
            True if successfully called and updated state, False otherwise
        """
        # 1. Retrieve candidate tools
        state_summary = state.get_summary()
        candidate_tools = self.retriever.retrieve(
            query=action.content or query,
            state_summary=state_summary,
            top_k=25
        )
        
        # 2. Try tools in order
        for tool_name in candidate_tools:
            if tool_name in self.failed_tools:
                continue
            
            if tool_name not in self.tool_contracts:
                continue
            
            contract = self.tool_contracts[tool_name]
            
            # 3. Check precondition
            satisfied, reason = self.precondition_checker.check_with_reason(
                state, contract
            )
            
            if not satisfied:
                # Precondition not satisfied, try next
                continue
            
            # 4. Generate tool parameters
            tool_params = self._generate_tool_params(
                contract, state, action
            )
            
            # 5. Call tool
            try:
                result = self.tool_executor.execute(
                    tool_name, tool_params, contract.input_schema
                )
            except Exception as e:
                # Tool call failed
                self.failed_tools.add(tool_name)
                continue
            
            trace_entry.tool_called = tool_name
            trace_entry.tool_result = result
            
            # 6. Verify postcondition
            success, error_msg, updates = self.postcondition_verifier.verify(
                state, contract, result
            )
            
            trace_entry.verification_result = {
                "success": success,
                "error_message": error_msg
            }
            
            if success:
                # 7. Update state
                new_state = state.update(updates)
                trace_entry.state = new_state
                trace_entry.state_updated = True
                
                # Update current state (note: need to return new state, but Python needs special handling)
                # In practice, caller needs to receive updated state
                
                # 8. Wrap tool result and add to history
                tool_result_wrapped = self.prompt_template.wrap_tool_result(
                    tool_name, result
                )
                self.tool_results_history.append(tool_result_wrapped)
                
                # Update conversation history (add tool result)
                self.conversation_history.append({
                    "role": "user",
                    "content": tool_result_wrapped
                })
                
                # Record trace
                self.trace.append(trace_entry)
                
                # Return success flag and new state
                return True, new_state
            else:
                # Verification failed, mark tool as failed
                self.failed_tools.add(tool_name)
                trace_entry.verification_result["error_message"] = error_msg
                continue
        
        # All tools failed
        # Note: Don't add trace here, handled uniformly by main loop
        # This avoids duplicate recording and allows main loop to add failure feedback
        return False, state
    
    def _generate_tool_params(self, contract: ToolContract,
                             state: SymbolicState, action: Action) -> Dict[str, Any]:
        """
        Generate tool call parameters
        
        Extract parameter values from state
        """
        params = {}
        
        if contract.input_schema:
            properties = contract.input_schema.get("properties", {})
            required = contract.input_schema.get("required", [])
            
            for param_name in required:
                # Try to get from state
                value = state.get_field(param_name)
                if value is not None:
                    params[param_name] = value
                else:
                    # If not in state, use default or extract from action
                    # Simplified here
                    params[param_name] = None
        
        return params
    
    def _format_trace(self) -> List[Dict[str, Any]]:
        """Format execution trace"""
        formatted = []
        for entry in self.trace:
            trace_dict = {
                "step": entry.step,
                "state_summary": entry.state.get_summary(),
                "action_type": entry.action.type if entry.action else None,
                "action_content": entry.action.content if entry.action else None,
                "tool_called": entry.tool_called,
                "tool_result": entry.tool_result,
                "verification_result": entry.verification_result,
                "state_updated": entry.state_updated
            }
            formatted.append(trace_dict)
        return formatted

